name: 'Post to Slack'
description: 'post message to slack'
inputs:
  message:
    description: 'message to post'
    required: true
  link_names:
    description: 'if this value set to true, find and link channel names and usernames'
outputs:
  status:
    description: 'status of post to stack'
runs:
  using: 'node12'
  main: 'dist/index.js'