name: test for post-to-slack for release

on: [release]
  types: [published]

jobs:
  run_release_test:
    runs-on: ubuntu-latest
    steps:
      - name: post message to slack
        id: post
        uses: chihirof/post-to-slack@v0.2.0
        env:
          WEBHOOKURL: ${{ secrets.WEBHOOKURL_CI_TEST }}
        with:
          message: from github actions for release test
      - name: Get the output [post message to slack]
        run: echo ${{ steps.post.outputs.status }}
