name: test for post-to-slack

on: [pull_request]

jobs:
  ci_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: post message to slack [OK]
        id: post
        uses: ./
        env:
          WEBHOOKURL: ${{ secrets.WEBHOOKURL_CI_TEST }}
        with:
          message: from github actions for test
      - name: Get the output [post message to slack]
        run: echo ${{ steps.post.outputs.status }}

      - name: missing WEBHOOKURL [Failed]
        id: missing-webhookurl
        uses: ./
        with:
          message: from github actions for test
        continue-on-error: true
      - name: check - missing WEBHOOKURL [Failed]
        run: ./bin/assert.sh ${{ steps.missing-webhookurl.outcome }} failure
      
      - name: invalid WEBHOOKURL [Failed]
        id: invalid-webhookurl
        uses: ./
        env:
          WEBHOOKURL: invalidurl
        with:
          message: from github actions for test
        continue-on-error: true
      - name: check - invalid WEBHOOKURL [Failed]
        run: ./bin/assert.sh ${{ steps.invalid-webhookurl.outcome }} failure
      
      - name: missing message [Failed]
        id: missing-message
        uses: ./
        env:
          WEBHOOKURL: ${{ secrets.WEBHOOKURL_CI_TEST }}
        continue-on-error: true
      - name: check - missing message [Failed]
        run: ./bin/assert.sh ${{ steps.missing-message.outcome }} failure
